name: S3 Terraform CI/CD

on:
  pull_request:
    branches: [ main ]
    paths: [ 's3-project/**' ]
  push:
    branches: [ main ]
    paths: [ 's3-project/**' ]

env:
  TF_VERSION: 1.12.2
  TFLINT_VERSION: v0.52.0
  AWS_REGION: us-east-1
  PROJECT: s3

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./s3-project
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - name: Run TFLint
        id: tflint
        run: tflint --init && tflint

      - name: Comment TFLint Results
        if: failure() && github.event_name == 'pull_request'
        uses: GetTerminus/terraform-pr-commenter@v1
        with:
          job: tflint
          id: tflint
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        id: validate
        run: terraform init -backend=false && terraform validate

  security-scan:
    name: Security Scan
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./s3-project
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run TFSec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  plan:
    name: Plan
    needs: [lint, security-scan]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./s3-project
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          # Run plan and capture exit code
          terraform plan -lock=false -input=false -no-color | tee tf_plan.txt
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          
          # Create a summary of changes
          terraform show -no-color -json $(terraform plan -lock=false -input=false -no-color -out=tfplan.binary >/dev/null && echo tfplan.binary) 2>/dev/null | \
            jq -r '[.resource_changes[] | {action: .change.actions[0], address: .address}] | group_by(.action)[] | "\(.[0].action | ascii_upcase) (\(length)): \(map(.address) | join(", "))"' | \
            tee tf_summary.txt

      - name: Comment Plan Results
        if: github.event_name == 'pull_request'
        uses: GetTerminus/terraform-pr-commenter@v3
        with:
          commenter_type: plan
          commenter_plan_path: tf_plan.txt
          commenter_plan_header: "## Terraform Plan Summary\n\n$(cat tf_summary.txt)"
          commenter_exitcode: ${{ steps.plan.outputs.exit_code }}
          commenter_append_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_WORKSPACE: ${{ inputs.terraform_workspace }}
